[package]
name = "matrix-game-2-inference"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
burn = { path = "../../crates/burn", features = ["ndarray"] }

